### ISSUE TITLE
diff import produces duplicates and/or negative osm_id's

### ISSUE THREAD

**Issue by bvbever** [omniscale/imposm3#51] opened 2015-05-18 07:45 UTC
first I take europe and import it with imposm3 with diff support:
```imposm3 import \```
```-connection postgis://xxx@xxx/osm_europe?sslmode=disable \```
```-cachedir="/home/PBFcache" \``` (cache is empty when I start to import)
```-diff=true \```
```-mapping /home/mapping_imposm3.json \```
```-read /home/europe-20150515.osm.pbf \```
```-dbschema-import="public" \``` (I do want to import directly to 'pubic')
```-write \```
```-appendcache``` (cache is empty when I start to import)

It takes about 5 hrs to insert the data.
Then I set an UNIQUE index on the column osm_id. I want to use them as unique values (what is normal, right ?)

Then I run dif 795 (next date with difs for europe-20150515.osm.pbf):
```imposm3 diff \```
```-cachedir='/home/PBFcache' \```
```-diffdir='/home/PBFcache' \```
```-dbschema-import='public' \```
```-mapping='/home/mapping_imposm3.json' \```
```-connection postgis://xxx@xxx/osm_europe?sslmode=disable \```
```/home/routeyou/pbf/dif/795.osc.gz```

Then I get 
1) the error duplicates on osm_id's => failed to insert.
2) I see that there are negative osm_ids ?? Whats the reason ? Can I delete them or not ?

**Comment by olt** [comment] 2015-05-18 08:05
It depends on your mapping. The example mapping inserts ways with rail=tram and highway=* as two separate geometries. See: http://imposm.org/docs/imposm3/latest/mapping.html#mappings

Negative IDs see http://imposm.org/docs/imposm3/latest/mapping.html#id

**Comment by bvbever** [comment] 2015-05-18 08:36
1) My mapping contains:
```javascript
"mappings": {
    "roads": {
        "mapping": {
            "highway": ["__any__"],
            "route": ["ferry"]
        }
    }
}
```
How can I be sure that only one osm_id is returned ?

2) Thanks for explaining negative id's

**Comment by olt** [comment] 2015-05-18 09:04
Imposm does not enforce UNIQUEness of OSM IDs. You can get multiple rows with the same ID for
- imports with `mappings`
- imports with -limitto (when a geometry has multiple overlaps)
- importing a diffs that overlaps the original import dataset (e.g. diff creates a way that is already imported) <- this is likely your case

**Comment by bvbever** [comment] 2015-05-18 14:40
It seams your last reason is the correct one.
can you tell me what code I have to alter to ignore failed insert/updates ? (I can alter my own version then)
now I get 
```[2K[May 18 13:18:48] [WARN] [writer] SQL Error: pq: current transaction is aborted, commands ignored until end of transaction block``` 
so it doesn't do anything...

**Comment by olt** [comment] 2015-09-09 10:12
Closing this as OSM IDs are not unique in Imposm imports by design. Imposm should work as expected without the custom index.

**Closed by olt** 2015-09-09 10:12 UTC
